events { worker_connections 1024; }

http {
    server {
        listen 80;
        server_name example.devopsatolyesi.local;

        # TODO: Let's Encrypt / Certbot ACME challenge dizinini tanımlayın
        # location /.well-known/acme-challenge/ {
        #     root /var/www/certbot;
        # }

        # TODO: Tüm HTTP trafiğini HTTPS'e yönlendirin (301 redirect)
        location / {
            return 200 "HTTP Insecure Server\n";
        }
    }
}
