apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: identity-system
data:
  devops-atolyesi-realm.json: |
    {
      "realm": "devops-atolyesi",
      "enabled": true,
      "displayName": "DevOps Atölyesi",
      "roles": {"realm": [
        {"name": "admin", "description": "Tüm eğitimleri ve yönetimi görür"},
        {"name": "instructor", "description": "Atandığı eğitimleri ve çözümleri görür"},
        {"name": "student", "description": "Atandığı eğitim lablarını görür"}
      ]},
      "groups": [
        {"name": "admins", "attributes": {"portal_role": ["admin"]}},
        {"name": "devops-practitioner-5-day", "attributes": {"course": ["devops-practitioner-5-day"]}},
        {"name": "docker-kubernetes-2-day", "attributes": {"course": ["docker-kubernetes-2-day"]}}
      ],
      "clients": [{
        "clientId": "labs-portal",
        "enabled": true,
        "protocol": "openid-connect",
        "publicClient": false,
        "standardFlowEnabled": true,
        "directAccessGrantsEnabled": false,
        "redirectUris": ["https://labs.devopsatolyesi.com/*"],
        "webOrigins": ["https://labs.devopsatolyesi.com"],
        "attributes": {"post.logout.redirect.uris": "https://labs.devopsatolyesi.com/*"}
      }]
    }
