input {
  beats {
    port => 5044
  }
}

filter {
  if [event][dataset] == "nginx.access" {
    grok {
      match => {
        "message" => '%{IPORHOST:[client][ip]} %{DATA:[nginx][access][ident]} %{DATA:[user][name]} \[%{HTTPDATE:[nginx][access][time]}\] "%{WORD:[http][request][method]} %{DATA:[url][original]} HTTP/%{NUMBER:[http][version]}" %{INT:[http][response][status_code]:int} (?:%{INT:[http][response][body][bytes]:int}|-) "(?<[http][request][referrer]>[^"]*)" "(?<[user_agent][original]>[^"]*)"'
      }
      add_tag => ["nginx_access_parsed"]
      tag_on_failure => ["_grok_nginx_access_failure"]
    }

    if "nginx_access_parsed" in [tags] {
      date {
        match => ["[nginx][access][time]", "dd/MMM/yyyy:HH:mm:ss Z"]
        target => "@timestamp"
        remove_field => ["[nginx][access][time]"]
      }

      useragent {
        source => "[user_agent][original]"
        target => "[user_agent]"
      }

      if [client][ip] and [client][ip] !~ /^(127\.|10\.|172\.(1[6-9]|2[0-9]|3[0-1])\.|192\.168\.)/ {
        geoip {
          source => "[client][ip]"
          target => "[source][geo]"
        }
      }

      if [http][response][status_code] >= 500 {
        mutate {
          add_field => { "[event][outcome]" => "failure" }
          add_tag => ["incident_candidate"]
        }
      } else {
        mutate { add_field => { "[event][outcome]" => "success" } }
      }
    }
  } else if [event][dataset] == "nginx.error" {
    grok {
      match => {
        "message" => '%{DATA:[nginx][error][time]} \[%{LOGLEVEL:[log][level]}\] %{NUMBER:[process][pid]:int}#%{NUMBER:[process][thread][id]:int}: (?:\*%{NUMBER:[nginx][error][connection_id]:int} )?%{GREEDYDATA:[error][message]}'
      }
      add_tag => ["nginx_error_parsed"]
      tag_on_failure => ["_grok_nginx_error_failure"]
    }
    mutate { add_field => { "[event][outcome]" => "failure" } }
  }

  mutate {
    add_field => {
      "[labels][lab_id]" => "LAB-LOG-01"
      "[labels][pipeline]" => "nginx-filebeat-logstash"
    }
    remove_field => ["agent", "ecs", "input", "log", "[host][mac]", "[host][ip]"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "devops-nginx-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }
}
