events { worker_connections 1024; }

http {
    server {
        listen 80;
        server_name example.devopsatolyesi.local;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name example.devopsatolyesi.local;

        ssl_certificate /etc/letsencrypt/live/example.devopsatolyesi.local/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.devopsatolyesi.local/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            default_type text/html;
            return 200 "<h1>HTTPS Secure Nginx with Let's Encrypt</h1>\n";
        }
    }
}
