pipeline {
    agent any
    environment {
        IMAGE_NAME = "payment-service"
        HARBOR_REGISTRY = "localhost:8082"
        HARBOR_PROJECT = "devops"
    }
    stages {
        stage('Checkout') {
            steps { echo "--> [1] Checkout SCM..." }
        }
        stage('Quality Gate') {
            steps { echo "--> [2] SonarQube Quality Gate Analysis..." }
        }
        stage('Docker Build') {
            steps {
                echo "--> [3] Docker multi-stage build..."
                sh 'docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} .'
            }
        }
        stage('Trivy Security Gate') {
            steps {
                echo "--> [4] Trivy vulnerability scan..."
                sh 'trivy image --severity CRITICAL --exit-code 1 --ignore-unfixed ${IMAGE_NAME}:${BUILD_NUMBER}'
            }
        }
        stage('Harbor Push') {
            steps { echo "--> [5] Push to Harbor OCI registry..." }
        }
    }
}
