apiVersion: v1
kind: Pod
metadata:
  name: writer
  namespace: lab-k8s-08
spec:
  volumes:
  - name: my-data
    persistentVolumeClaim:
      claimName: app-data
  containers:
  - name: writer
    image: busybox:1.36.1
    command: ["sh", "-c", "date -u > /data/evidence.txt; cat /data/evidence.txt; sleep 3600"]
    volumeMounts:
    - name: my-data
      mountPath: /data
