image:
  repository: harbor.devopsatolyesi.com/library/labs-portal
  tag: feabe7b9bba0
  pullPolicy: Always
imagePullSecrets:
  - name: harbor-registry
replicas: 2
hostname: labs.devopsatolyesi.com
ingressClassName: nginx
servicePort: 80
auth:
  enabled: true
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.12.0
  existingSecret: labs-auth-secrets
  issuerURL: https://auth.devopsatolyesi.com/realms/devops-atolyesi
  clientID: labs-portal
