pid /tmp/nginx.pid;
events { worker_connections 1024; }
http {
    client_body_temp_path /tmp/client_temp;
    server {
        listen 8080;
        location / {
            return 200 '{"status":"secure"}\n';
            add_header Content-Type application/json;
        }
    }
}
